/* eslint-disable */
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

declare global {
    interface Window {
        __TAURI_INVOKE__<T>(cmd: string, args?: Record<string, unknown>): Promise<T>;
    }
}

// Function avoids 'window not defined' in SSR
const invoke = () => window.__TAURI_INVOKE__;

export function createAccount(data: CreateAccountData) {
    return invoke()<Account>("create_account", { data })
}

export function getAccount() {
    return invoke()<Account>("get_account")
}

export function getAllAccounts() {
    return invoke()<Account[]>("get_all_accounts")
}

export type CreateAccountData = { account_type: string; name: string; amount: number }
export type Account = { id: string; type: string; name: string; amount: number; createdAt: string; updatedAt: string }
